---
title: "Data analysis"
author: "Xueying Feng"
date: "4/11/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
getwd()
setwd("~/Desktop/Environ 872/ENV872 Project_XY_Feng/Data/Processed")

library(lubridate)
require(dplyr)

require(ggplot2)
#install.packages("ggrepel") 
require(ggrepel)

```


## Analysis of United States Data

```{r}
#Import datasets
Covid19_US_processed <- read.csv("./Data/Processed/Covid19_US_processed.csv")

head(Covid19_US_processed)
str(Covid19_US_processed)

Covid19_US_processed$time <- as.Date(Covid19_US_processed$time, format = "%m/%d/%y") 
class(Covid19_US_processed$time)

```

## Draw maps

```{r}
# get column names
colnames(Covid19_US_processed)

# Rename column where names is "province"
names(Covid19_US_processed)[names(Covid19_US_processed) == "province"] <- "state"
str(Covid19_US_processed)


# Select total confirmed cases in 51 States
US_States <- Covid19_US_processed %>%
  filter(time >= as.Date("2020-04-16")) %>%
  filter(state!= "Unpublished sources") %>%
  top_n(51, cum_confirm)

# Convert state column to characters 
US_States$state <- as.character(US_States$state)

# rename specific cell name
US_States$state[US_States$state == 'New York state'] <- 'New York'
US_States$state[US_States$state == "Washington State"] <- "Washington"
US_States$state[US_States$state == 'the state of Wisconsin'] <- 'Wisconsin'


```

```{r, fig.cap=paste("Map of comfimed cases didtribution in United State")}
#install.packages("usmap")
library(usmap)

USMap_Base <- plot_usmap(regions = "counties") + 
  labs(title = "US Counties",
       subtitle = "This is a blank map of the counties of the United States.") + 
  theme(panel.background = element_rect(color = "black", fill = "lightblue"))


### Draw map
CasesDidtribution <- plot_usmap(regions="state", data = US_States, values = "cum_confirm", color = "black") +
  scale_fill_continuous(low = "#fee6ce", high = "#d95f0e", 
                        name = "Total confirmed cases", label = scales::comma) + 
  labs(title = "State Reporting Cases of Covid 19") +
  theme(legend.position = "right")

print(CasesDidtribution)
```

## Draw trend of each states in United States

```{r, fig.cap=paste("Trend of each states in United States")}
# Create a ggplot depicting cases incereasing over time in each state
US_State_Trend <- ggplot(Covid19_US_processed, aes(x=time, y=cum_confirm, color=state)) +
    geom_line(alpha = 0.95, size = 0.5) +
    geom_text_repel(aes(label=state),
                    function(Covid19_US_processed) 
                      Covid19_US_processed[Covid19_US_processed$time == as.Date("2020-04-16"),])+
    mytheme +
    theme(legend.position = "none") +
    labs(x=expression(paste("Time"))) + 
    labs(y=expression(paste("Comfimed Cases")))+
    labs(color="Covid19_US_processed") +
    scale_x_date(date_labels = "%Y-%m-%d") 

print(US_State_Trend)
```

## Draw trend of top ten states in United States (except NY and NJ)
```{r}

TopTen_States <- Covid19_US_processed %>%
  filter(time >= as.Date("2020-04-16")) %>%
  filter(state!= "New York state" & state!= "New Jersey" & state!= "Unpublishedsources") %>%
  top_n(10, cum_confirm) %>%
  arrange(desc(cum_confirm))

TopTen_States <- pull(TopTen_States, state)

TenStates_US <- Covid19_US_processed %>% 
  filter(state %in% TopTen_States) 

str(TenStates_US)

# Save as csv
write.csv(TenStates_US,
          file = "./Data/Processed/TenStates_US (except NY and NJ).csv")
```


```{r, fig.cap=paste("Trend of top ten states in United States (except NY and NJ)")}
# Create a ggplot 
TenStates_trend <- ggplot(TenStates_US, aes(x = time, y =cum_confirm, color=state)) +
  geom_line(alpha = 0.95, size = 1) +
  geom_text_repel(aes(label=state),
                      function(TenStates_US) 
                      TenStates_US[TenStates_US$time == as.Date("2020-04-16"),])+
  mytheme +
  theme(legend.position = "none") +
  labs(x=expression(paste("Time"))) + 
  labs(y=expression(paste("Comfimed Cases"))) +
  labs(color="state") +
  scale_x_date(date_labels = "%Y-%m-%d")


print(TenStates_trend)
```

## Trend analysis of comfirmed cases, dead cases, and heal cases
```{r")}
Historical_USTrend = Historical_Global_processed[Historical_Global_processed$country == 'United States',] %>%
  na.omit(Historical_USTrend)

tail(Historical_USTrend)

# Save as csv
write.csv(Historical_USTrend,
          file = "./Data/Processed/Historical_USTrend.csv",row.names=FALSE)

```

## Increasing case trend in US

```{r, fig.cap=paste("Trend of confirmed case in the U.S. from Dec-2019 to Apri-2020")}
US_ComfirmedCases_Trend <-
  ggplot(Historical_USTrend, aes(x = time, y = cum_confirm)) +
  geom_point(colour = "#e6550d") +
  geom_line(colour = "#d95f0e") +
  labs(x = "Time", 
       y = "Confirmed Cases") + 
  scale_x_date(date_labels = "%Y-%m-%d")

print(US_ComfirmedCases_Trend)
```

## Trend anlysis on confirmed, heal, dead number

```{r}
# Change Historical_USTrend dataset's Column names
str(Historical_USTrend)

names(Historical_USTrend)[1] <- "Time"
names(Historical_USTrend)[3] <- "Total Confirm"
names(Historical_USTrend)[4] <- "Total Heal"
names(Historical_USTrend)[5] <- "Total Dead"

USTrend_gather <- tidyr::gather(Historical_USTrend, "Type", "Number", 3:5)
str(USTrend_gather)
```


```{r, fig.cap=paste("Number of deaths, confirms, and cures in US")}
US_Trend <- ggplot(USTrend_gather, aes(Time, Number, color = Type)) +
  geom_point() + 
  geom_line() + 
  labs(x=expression(paste("Time"))) + 
  labs(y=expression(paste("Total number")))+
  mytheme + 
  theme(legend.position = "right") +
  scale_x_date(date_labels = "%Y-%m-%d", 
    limits = c(as.Date("2020-01-15"), as.Date("2020-04-16"))) +
  labs(title="Number of deaths, confirms, and cures in US") 
print(US_Trend)


```

## Draw heal and dead plot 

```{r}
head(TenStates_US)

names(TenStates_US)[1] <- "Time"
names(TenStates_US)[4] <- "Total Confirm"
names(TenStates_US)[5] <- "Total Heal"
names(TenStates_US)[6] <- "Total Dead"

TenStates_US_gather <- tidyr::gather(TenStates_US, "Type", "Number", 4:6)
str(TenStates_US_gather)
```


```{r, fig.cap=paste("Number of deaths, confirms, and cures in top ten states")}
US_Topten_Trend <-
  ggplot(TenStates_US_gather, aes(x = Time, y = Number, color = Type)) +
  geom_line() +
  geom_point() +
  labs(x=expression(paste("Time"))) + 
  labs(y=expression(paste("Total number")))+
  mytheme + 
  theme(legend.position = "right") +
  facet_wrap(.~state)
print(US_Topten_Trend)

```






