---
title: "Data processing"
author: "Xueying Feng"
date: "4/11/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
## Get Novel Coronavirus Data

```{r}
library('remotes')
remotes::install_github("GuangchuangYu/nCov2019",force = TRUE)
```

## Access China's COVID-19 data 

```{r}
library(nCov2019)
nCov2019 = get_nCov2019(lang='en')

nCov2019 

# create table
Covid19_China <- nCov2019[] 

# Save to csv.
write.csv(Covid19_China, row.names = FALSE, file = "./Data/Raw/Covid19_China_raw.csv")
```

## Access Hubei Province COVID-19 data 

```{r}
Covid19_Hubei <- nCov2019['Hubei']

# Save to csv.
write.csv(Covid19_Hubei, row.names = FALSE, file = "./Data/Raw/Covid19_Hubei_raw.csv")
```


## Access Global COVID-19 data 

```{r}
Covid19_Global <- nCov2019['global']
write.csv(Covid19_Global, row.names = FALSE, file = "./Data/Raw/Covid19_Global_raw.csv")

```

## Access China's Historical data

```{r}
library('nCov2019')
nCov2019_history <- load_nCov2019(lang = 'en')

nCov2019_history

# create table
historical_China <- nCov2019_history[] 

# Save to csv.
write.csv(historical_China, row.names = FALSE, file = "./Data/Raw/historical_China_raw.csv")
```

## Access Global's Historical data

```{r}
nCov2019_history <- load_nCov2019(lang = 'en', source='github')
historical_Global <- nCov2019_history['global']

# Check data
tail(historical_Global)

# Save to csv.
write.csv(historical_Global, row.names = FALSE, file = "./Data/Raw/historical_Global_raw.csv")
```

## Access Italy cumulative confirm data

```{r}
nCov2019_set_country('Italy') 
Italy <- load_nCov2019(lang = 'en', source = 'github')

# Check data
# This will return province data of Italy
head(Italy['province']) 

Covid19_Italy <- Italy['province']

# Save to csv.
write.csv(Covid19_Italy, row.names = FALSE, file = "./Data/Raw/Covid19_Italy_raw.csv")

```

## Access United States cumulative confirm data

```{r}
nCov2019_set_country('United States') 
theUS <- load_nCov2019(lang = 'en', source = 'github')

# Check data
# This will return province data of United States
head(theUS['province']) 

Covid19_US <- theUS['province']

# Save to csv.
write.csv(Covid19_US, row.names = FALSE, file = "./Data/Raw/Covid19_US_raw.csv")

```

## Access United Kingdom cumulative confirm data

```{r}
nCov2019_set_country('United Kingdom') 
theUK <- load_nCov2019(lang = 'en', source = 'github')

# Check data
# This will return province data of Spain
head(theUK['province']) 

Covid19_UK <- theUK['province']

# Save to csv.
write.csv(Covid19_UK, row.names = FALSE, file = "./Data/Raw/Covid19_UK_raw.csv")

```