---
title: "Data exploration"
author: "Xueying Feng"
date: "4/11/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
require(dplyr)

#Import datasets
Historical_Global_processed <- read.csv("./Data/Processed/Historical_Global_processed.csv")
```

## Set theme

```{r}
require(ggplot2)
#install.packages("ggrepel") 
require(ggrepel)

mytheme <- theme_minimal(base_size = 12, base_family = "Times") + 
  theme(axis.text.x = element_text(color = "DarkGrey"),
        legend.position = "top") 
theme_set(mytheme)

```

## Time series analysis
```{r, fig.cap=paste("Increasing case trend in China")}
#Selsct data from China
Historical_China = Historical_Global_processed[Historical_Global_processed$country == 'China',]
head(Historical_China)

# Change date column to date
Historical_China$time <- as.Date(Historical_China$time, format = "%Y-%m-%d") 
class(Historical_China$time)

# Create a ggplot depicting cases incereasing over time
China_Trend <- 
  ggplot(Historical_China, aes(x=time, y=cum_confirm)) +
  geom_point() +
  geom_line() +
  labs(x = "Date", 
       y = "Confirmed Cases") + 
  scale_x_date(date_labels = "%b %d")

print(China_Trend)


```

## TopTen_countries

```{r cars}
# Check on data frame
head(Historical_Global_processed)
str(Historical_Global_processed)

# Change date column to date
Historical_Global_processed$time <- as.Date(Historical_Global_processed$time, format = "%Y-%m-%d") 
class(Historical_Global_processed$time)

# Remove China data
Historical_Global = Historical_Global_processed[Historical_Global_processed$country != 'China',]
head(Historical_Global)

# Filter out the top ten countries with the highest number of diagnoses (except China)
TopTen_countries <- Historical_Global %>% 
  filter(time >= as.Date("2020-04-16")) %>%
  top_n(10, cum_confirm) %>%
  arrange(desc(cum_confirm)) 

# Selects a column in a data frame and transforms it into a vector
TopTen_countries <- pull(TopTen_countries, country)

Historical_TopTen <- filter(Historical_Global, country %in% TopTen_countries) %>%
  arrange(desc(cum_confirm))
str(Historical_TopTen)

```

## Plots trens of comfirmed cases in top ten coutries

```{r, fig.cap=paste("Top ten countries with the highest number of diagnoses (except China)")}

# Draw plot
ggplot(Historical_TopTen, aes(x = time, y =cum_confirm, color=country)) +
    geom_line(alpha = 0.95, size = 1) +
    geom_text_repel(aes(label=country),
                    function(Historical_TopTen) 
                      Historical_TopTen[Historical_TopTen$time == as.Date("2020-04-16"),])+
    mytheme +
    theme(legend.position = "none") +
    labs(x=expression(paste("Month"))) + 
    labs(y=expression(paste("Comfimed Cases")))+
    labs(color="Country")

```


## Analysis of each province in China 

```{r}
#Import datasets
Historical_China_processed <- read.csv("./Data/Processed/Historical_China_processed.csv",header = TRUE)

head(Historical_China_processed)
str(Historical_China_processed)

# Change date column to date
Historical_China_processed$time <- as.Date(Historical_China_processed$time, format = "%m/%d/%y") 
head(Historical_China_processed)
class(Historical_China_processed$time)

# Remove Hubei province data
Historical_ChinaProvince = Historical_China_processed[Historical_China_processed$province != 'Hubei',]
head(Historical_ChinaProvince)

Historical_ChinaProvinceV2 <- Historical_ChinaProvince %>%
  group_by(time,province) %>%
  summarise(total_confirm = sum(cum_confirm))
```

## Draw trend line of each province
```{r, fig.cap=paste("Increase cases trend in each province, China (except Hubei)")}
# Create a ggplot depicting cases incereasing over time
Province_Trend <- ggplot(Historical_ChinaProvinceV2, aes(x=time, y=total_confirm, color=province)) +
    geom_line(alpha = 0.95, size = 1) +
    geom_text_repel(aes(label=province),
                    function(Historical_ChinaProvinceV2) 
                      Historical_ChinaProvinceV2[Historical_ChinaProvinceV2$time == as.Date("2020-04-16"),])+
    mytheme +
    theme(legend.position = "none") +
    labs(x=expression(paste("Month"))) + 
    labs(y=expression(paste("Comfimed Cases")))+
    labs(color="province")

print(Province_Trend)
```

## Top ten province in China
```{r}
# Filter out the top ten provinces with the highest number of diagnoses (except Hubei)
TopTen_provinces <- Historical_ChinaProvinceV2 %>% 
  filter(time >= as.Date("2020-04-16")) %>%
  top_n(10, total_confirm) %>%
  arrange(desc(total_confirm)) 

TopTen_provinces <- pull(TopTen_provinces, province)

TenProvinces_China <- filter(Historical_ChinaProvinceV2, province %in% TopTen_provinces) %>%
  arrange(desc(total_confirm))
str(TopTen_provinces)
```

```{r, fig.cap=paste("Top ten provinces with the highest number of diagnoses, China (except Hubei)")}
# Draw plot
ggplot(TenProvinces_China, aes(x = time, y =total_confirm, color=province)) +
    geom_line(alpha = 0.95, size = 1) +
    geom_text_repel(aes(label=province),
                    function(Historical_ChinaProvinceV2) 
                      Historical_ChinaProvinceV2[Historical_ChinaProvinceV2$time == as.Date("2020-04-16"),])+
    mytheme +
    theme(legend.position = "none") +
    labs(x=expression(paste("Month"))) + 
    labs(y=expression(paste("Comfimed Cases")))+
    labs(color="province")

```
